repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: file-contents-sorter
        files: "dictionaries/main.txt"
        args: ["--unique"]
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://git.afpy.org/AFPy/powrap
    rev: 416de333cc58dce4453d1257769d7c9abdde95f7 # v1.0.2
    hooks:
      - id: powrap

  - repo: https://git.afpy.org/AFPy/pospell
    rev: 8b753bde26fe612ba397a4b4aafa7a0560402805 # v1.3
    hooks:
      - id: pospell
        args:
          - "--language=el_GR"
          - "--personal-dict=dictionaries/main.txt"

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: ff671d6a030a3141634793e6d1e8909ab6091830 # v1.0.0
    hooks:
      - id: sphinx-lint
